# This is a basic workflow to help you get started with Actions

name: Build Image

# Controls when the action will run. 
on: 
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Fetch Last Sponge Build
        id: sponge-check
        run: |
          ./fetch-versions.sh

